/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyIdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "MyUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}